# Generated by Django 4.2.6 on 2023-10-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobilenum', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
